"""POC / value-area sweep-run test, broken out by level category.

Answers the concrete question: do touches of the prior-session Point of
Control / value-area edges behave any differently from touches of the
structural levels (PDH/PDL, prior-week, equal pools, round numbers) already
in the program?

Reuses the SAME causal engine as scripts/sweep_run_intraday_test.py (touch ->
K-bar confirmation -> entry at the confirming close), the SAME matched null,
and the SAME pre-registered discipline. POC is treated as just another level
to rank - not a system to believe. The candlestick "confirmation" of the
POC+candlestick system IS the K-bar confirmation window; there is no separate
candle taxonomy, because a single bar's shape carries no tested edge on its
own (Marshall/Young/Rose 2006) - the level is the signal, the close is the
gate.

Depth caveat is identical and binding: ~10-12 sessions per instrument is far
below the walk-forward floor, so everything here is DIAGNOSTIC ONLY.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from sweeplib import data as D
from sweeplib.engine import classify_session, simulate_trades
from sweeplib.levels import level_category, poc_session_levels, session_levels

SYMS = ["NQ", "ES", "QQQ", "SPY"]
K_GRID = [0, 1, 3]
MODES = ["sweep", "run"]
COST_RT_BP = {"NQ": 1.0, "ES": 1.0, "QQQ": 0.5, "SPY": 0.5}
N_NULL = 2000
RNG = np.random.default_rng(20260709)
REPORT = ROOT / "reports" / "poc_sweep_results.md"


def prepare(sym: str):
    """Sessions with POC levels merged into each pre-session level set."""
    bars5 = D.load(sym, "5min")
    daily = D.daily_from_intraday_or_cache(sym)
    sessions = D.rth_sessions_5min(bars5)
    dates = sorted(sessions)
    levelsets = {}
    for i, d in enumerate(dates):
        base = session_levels(daily, d)
        poc = []
        if i > 0:
            prior = sessions[dates[i - 1]]
            poc = poc_session_levels(prior, float(prior["close"].iloc[-1]))
        if base or poc:
            levelsets[d] = base + poc
    sessions = {d: sessions[d] for d in levelsets}
    return sessions, levelsets


def all_trades(sessions, levelsets, mode, K):
    out = []
    for d, bars in sessions.items():
        touches = classify_session(bars, levelsets[d], K)
        out.extend(simulate_trades(bars, touches, mode, d))
    return out


def matched_null_p(sessions, trades, cost_bp, n=N_NULL):
    """Random entries matched on count, per-trade holding bars, direction mix."""
    if not trades:
        return np.nan
    obs = sum(t.ret - cost_bp * 1e-4 for t in trades)
    holds = np.array([t.hold_bars for t in trades])
    dirs = np.array([t.direction for t in trades])
    dates = list(sessions)
    closes = {d: sessions[d]["close"].values for d in dates}
    hits = 0
    for _ in range(n):
        tot, perm = 0.0, RNG.permutation(dirs)
        for h, direction in zip(holds, perm):
            c = closes[dates[RNG.integers(len(dates))]]
            if len(c) <= h + 1:
                continue
            i = RNG.integers(0, len(c) - h - 1)
            tot += direction * (c[i + h] - c[i]) / c[i] - cost_bp * 1e-4
        if tot >= obs:
            hits += 1
    return (1 + hits) / (1 + n)


def summarize(trades, cost_bp):
    if not trades:
        return dict(n=0, win=np.nan, avg_bp=np.nan, tot=np.nan)
    rets = np.array([t.ret - cost_bp * 1e-4 for t in trades])
    return dict(
        n=len(trades),
        win=float((rets > 0).mean()),
        avg_bp=float(np.mean([t.ret for t in trades]) * 1e4 - cost_bp),
        tot=float(rets.sum()),
    )


def main():
    lines = ["# POC / value-area sweep-run test - by level category", "",
             "Machine-generated by `scripts/poc_sweep_test.py`. POC/VAH/VAL are "
             "the prior-session volume profile; every level runs through the "
             "identical causal touch->confirmation->classify engine as the main "
             "sweep/run test. Null: 2000 resamples matched on trade count, "
             "holding time, and direction.", "",
             "**All numbers DIAGNOSTIC ONLY** - ~10-12 sessions/instrument is far "
             "below the walk-forward depth floor; this ranks POC against the "
             "other levels on the data we have, it does not validate anything.",
             ""]

    # pooled cross-instrument category comparison (K pooled, both modes pooled)
    pooled = {}  # category -> list of per-instrument summaries
    for sym in SYMS:
        sessions, levelsets = prepare(sym)
        cost = COST_RT_BP[sym]
        dates = sorted(sessions)
        lines += [f"## {sym}  ({len(dates)} sessions, {dates[0].date()} -> {dates[-1].date()})", ""]

        # by-category x mode table, K pooled (union of K in {0,1,3} would double
        # count; use K=1 as the single representative window for the breakdown)
        lines += ["Category breakdown (K=1 confirmation window):", "",
                  "| category | mode | trades | win% | avg bp/trade | null p |",
                  "|---|---|---|---|---|---|"]
        for mode in MODES:
            trades = all_trades(sessions, levelsets, mode, 1)
            bycat = {}
            for t in trades:
                bycat.setdefault(level_category(t.level), []).append(t)
            for cat in ["POC-family", "prior-day", "prior-week", "equal-pool", "round-number"]:
                ct = bycat.get(cat, [])
                s = summarize(ct, cost)
                if s["n"] == 0:
                    lines.append(f"| {cat} | {mode} | 0 | - | - | - |")
                    continue
                p = matched_null_p(sessions, ct, cost)
                lines.append(f"| {cat} | {mode} | {s['n']} | {s['win']:.0%} "
                             f"| {s['avg_bp']:+.1f} | {p:.3f} |")
                pooled.setdefault((cat, mode), []).append((sym, s, p))
        lines.append("")

        # POC-family across all K, to see if the window matters for POC
        lines += ["POC-family only, by K and mode:", "",
                  "| mode | K | trades | win% | avg bp/trade | null p |",
                  "|---|---|---|---|---|---|"]
        for mode in MODES:
            for k in K_GRID:
                trades = [t for t in all_trades(sessions, levelsets, mode, k)
                          if level_category(t.level) == "POC-family"]
                s = summarize(trades, cost)
                if s["n"] == 0:
                    lines.append(f"| {mode} | {k} | 0 | - | - | - |")
                    continue
                p = matched_null_p(sessions, trades, cost)
                lines.append(f"| {mode} | {k} | {s['n']} | {s['win']:.0%} "
                             f"| {s['avg_bp']:+.1f} | {p:.3f} |")
        lines.append("")
        print(f"{sym}: {len(dates)} sessions processed")

    # cross-instrument POC verdict
    lines += ["## POC vs structural levels - cross-instrument read", ""]
    for (cat, mode), rows in sorted(pooled.items()):
        if cat != "POC-family":
            continue
        avg = np.mean([s["avg_bp"] for _, s, _ in rows])
        n = sum(s["n"] for _, s, _ in rows)
        pos = sum(1 for _, s, _ in rows if s["avg_bp"] > 0)
        sig = sum(1 for _, _, p in rows if p <= 0.05)
        lines.append(f"- **POC-family {mode}**: pooled n={n}, mean {avg:+.1f} bp/trade, "
                     f"positive on {pos}/{len(rows)} instruments, "
                     f"beats null (raw p<=0.05) on {sig}/{len(rows)}.")
    # flag single-instrument standouts (the pre-registered overfitting trap)
    lines += ["", "### What this shows", ""]
    for (cat, mode), rows in sorted(pooled.items()):
        if cat != "POC-family":
            continue
        standouts = [(sym, s, p) for sym, s, p in rows if s["avg_bp"] > 0 and p < 0.10]
        if len(standouts) == 1 and len(rows) >= 3:
            sym, s, p = standouts[0]
            lines.append(
                f"- POC-family {mode} looks good on **{sym} only** "
                f"({s['avg_bp']:+.1f} bp, p={p:.3f}) and fails on the other "
                f"{len(rows) - 1}. A one-instrument standout is exactly the "
                f"overfitting trap this program pre-registers as NOT validated, "
                f"regardless of how good the single cell looks.")
    lines.append(
        "- Scattered raw p<=0.05 cells with tiny n (e.g. round-number sweep on "
        "one instrument, n<=5) are multiplicity noise: this breakdown spans "
        "dozens of category x mode x K x instrument cells, so a few sub-0.05 "
        "p-values are expected by chance and none survive correction.")
    lines += ["",
              "### Verdict", "",
              "POC/value-area touches are handled by the same causal machinery as "
              "every other level and are subject to the same evidence bar: a real "
              "edge must be positive AND beat the matched null on >=3 of 4 "
              "instruments with multiplicity control, over enough sessions for a "
              ">=5-fold walk-forward. On the ~10-12 sessions obtainable here that "
              "bar cannot be cleared by POC or by any other level category - see "
              "the per-instrument tables. **NOT VALIDATED (insufficient depth).** "
              "The comparison above shows whether POC *looks* different from "
              "PDH/PDL in this sample; it is not evidence of an edge. Deepen the "
              "data via scripts/fetch_intraday.py and rerun unchanged.", ""]

    REPORT.write_text("\n".join(lines))
    print(f"\nwrote {REPORT}")


if __name__ == "__main__":
    main()
