#!/usr/bin/env python3
"""RP-008 Stage 0 -- strategy, entry-time and regime-variable feasibility audit.

COUNTS ONLY. No conditional performance is computed anywhere in this file.
Unconditional expectancy, profit factor and drawdown are reported because the
Stage 0 brief requires them; NO strategy is ever split by regime here.

Every strategy is regenerated by calling its OWN frozen runner. Nothing is
refitted, no threshold is touched, no filter is added. Entry timestamps are
recovered by WRAPPING the frozen trade builders to observe the entry bar index
they already use -- the wrappers record and then delegate, so the rule executed
is byte-for-byte the committed one.

Usage: python3 scripts/orderflow/rp008_stage0.py
"""
from __future__ import annotations

import datetime as dt
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "reports"

# Frozen time-of-day blocks, minutes after the 09:30 ET cash open.
TOD = [("open 09:30-10:00", 0, 30),
       ("morning 10:00-11:30", 30, 120),
       ("midday 11:30-14:00", 120, 270),
       ("close 14:00-16:00", 270, 391)]


def tod_of(m):
    for name, a, b in TOD:
        if a <= m < b:
            return name
    return "outside"


def dd_R(r):
    """Max drawdown of the cumulative R curve, in R."""
    c = np.cumsum(np.asarray(r, float))
    return float(np.max(np.maximum.accumulate(c) - c)) if len(c) else np.nan


def pf(r):
    r = np.asarray(r, float)
    g, l = r[r > 0].sum(), -r[r < 0].sum()
    return float(g / l) if l > 0 else np.inf


def months_of(days):
    s = pd.to_datetime(pd.Series(list(days)))
    return int(s.dt.to_period("M").nunique())


# ---------------------------------------------------------------- library --
def orb_and_pullback():
    """The six QQQ ORB / pullback sets, straight from setup_grading's builder.

    setup_grading already records `mins` -- minutes since the cash open -- for
    every trade, so nothing needs wrapping here.
    """
    import or_height as OH
    import setup_grading as SG
    S1, _rej = OH.build("data/intraday_long/QQQ_1m.parquet", 1)
    T, _meta = SG.build_trades(S1)
    out = {}
    for name, g in T.groupby("setname"):
        out[name] = g.rename(columns={"mins": "m"})[
            ["day", "year", "R", "m", "risk_bps", "cost_risk"]].copy()
    return out


def ib_family_times():
    """Entry minutes for the IB family, recovered by replaying the frozen scan.

    This repeats reopen_study.test1's own arming logic verbatim in order to
    record the bar index it enters on. It computes no outcome and takes no
    decision the frozen runner does not already take.
    """
    import reopen_study as RS
    sess = RS.load()
    rows = []
    for S in sess:
        t, hi, lo, cl = S["t"], S["hi"], S["lo"], S["cl"]
        ib = (t >= 0) & (t < 60)
        n = len(t)
        if ib.sum() < 30 or (t >= 60).sum() < 60:
            continue
        ih, il = hi[ib], lo[ib]
        tib = t[ib]
        a, b = int(np.argmax(ih)), int(np.argmin(il))
        if tib[a] == tib[b]:
            continue
        ibh, ibl = float(ih[a]), float(il[b])
        rng = ibh - ibl
        if rng <= 0:
            continue
        high_first = tib[a] < tib[b]
        close = float(cl[ib][-1])
        exp_lvl = ibl if high_first else ibh
        if 100.0 * abs(close - exp_lvl) / rng >= 25:
            continue
        d = -1 if high_first else 1
        stop = ibh if high_first else ibl
        i0 = int(np.searchsorted(t, 60, "left"))
        fe = np.where(hi[i0:] > exp_lvl)[0] if d > 0 else np.where(lo[i0:] < exp_lvl)[0]
        fo = np.where(lo[i0:] < stop)[0] if d > 0 else np.where(hi[i0:] > stop)[0]
        if len(fe) == 0 or (len(fo) and int(fo[0]) < int(fe[0])):
            continue
        taken, i, armed = 0, i0, True
        while i < n and taken < 2:
            brk = hi[i] > exp_lvl if d > 0 else lo[i] < exp_lvl
            if armed and brk:
                fill = max(exp_lvl, S["op"][i]) if d > 0 else min(exp_lvl, S["op"][i])
                r = RS.run_trade(S, i, d, fill, stop, 1.0, n)
                if r:
                    taken += 1
                    rows.append(dict(day=S["day"], year=S["year"], dir=d,
                                     seq=taken, m=float(t[i]), R=r["R"],
                                     risk_bps=1e4 * r["risk"] / S["px"],
                                     cost_pct=100 * S["px"] * RS.COST_F / r["risk"]))
                    i = r["j"] + 1
                    armed = False
                    continue
            if not armed:
                inside = (lo[i] < exp_lvl) if d > 0 else (hi[i] > exp_lvl)
                if inside:
                    armed = True
            i += 1
    T = pd.DataFrame(rows)
    return {"IB 1R single": T[T.seq == 1].copy(), "IB 1R re-entry": T.copy()}


def orb_fib_times():
    """Entry minute for ORB-Fib continuation, taken from the 1-minute grid.

    The runner works on a per-session minute axis t where t = 0 is 09:30, and
    the continuation entry is the first bar strictly after confirmation at
    which the near-edge level is touched. The audit re-derives that bar index
    from the runner's own session objects.
    """
    import orb_fib as OF
    sess = OF.load()
    grab = {}
    orig = OF.manage

    def wrapped(hi, lo, op, cl, i_entry, fill, stop, naive_fill, direction,
                px, i_flat, *a, **k):
        grab.setdefault("i", []).append(int(i_entry))
        return orig(hi, lo, op, cl, i_entry, fill, stop, naive_fill,
                    direction, px, i_flat, *a, **k)

    OF.manage = wrapped
    out = {}
    try:
        for orb in (15, 30):
            grab.clear()
            rows = []
            for day, g in sess:
                o = pd.Timestamp(dt.datetime.combine(day, dt.time(9, 30)))
                t = (g.timestamp - o).dt.total_seconds().to_numpy() / 60.0
                before = len(grab.get("i", []))
                c, _r, _d = OF.session_setups(
                    day, t, g.high.to_numpy(float), g.low.to_numpy(float),
                    g.open.to_numpy(float), g.close.to_numpy(float),
                    orb, "A", False)
                new = grab.get("i", [])[before:]
                if c and new:
                    rows.append({**c, "m": float(t[new[0]])})
            T = pd.DataFrame(rows)
            if len(T):
                T["year"] = pd.to_datetime(T.day).dt.year
            out[f"ORB-Fib cont ORB{orb} A"] = T
    finally:
        OF.manage = orig
    return out


def compression_sets():
    """Compressed multi-day range continuation. Entry is the bar AFTER D.

    D is 10:00 or 10:30 ET by construction, so the entry minute is a constant
    per variant, not a distribution. The frozen BOTH arm and the frozen flat
    exit are used; no threshold is touched.
    """
    import compression as CP
    out, notes = {}, []
    S = CP.frame(CP.load())
    drift = CP.drift_fracs(S)
    for D, m in (("10:00", 31.0), ("10:30", 61.0)):
        T = CP.trades(S, D, "flat", drift)
        if T is None or not len(T):
            continue
        T = T.copy()
        T["m"] = m
        T["dir"] = T["d"]
        out[f"Compression D={D} flat"] = T
    return out, notes


def ib_midpoint_pullback():
    """IB midpoint pullback with R2 rejection -- the frozen QQQ specification.

    native_session is wrapped to observe the entry bar index it already picks.
    Both the frozen (ending-zone) arm and the native-normalised arm are
    reported, because the ledger contains both.
    """
    import ib_pullback_native as N
    cap = {}
    orig = N.mk

    def wrapped(S, d, fill, stop, risk, exi, why, cost, mfe, mae, amb, a, Q):
        r = orig(S, d, fill, stop, risk, exi, why, cost, mfe, mae, amb, a, Q)
        r["m"] = cap.get("last", np.nan)
        return r

    orig_enter = N.enter

    def wrapped_enter(S, Q, i_conf, d, pull_ext, atr, cost):
        # the frozen runner enters at i_conf + 1; record that bar's minute
        ie = i_conf + 1
        cap["last"] = (float(S["t"][ie]) if ie < len(S["t"]) else np.nan)
        return orig_enter(S, Q, i_conf, d, pull_ext, atr, cost)

    N.mk = wrapped
    N.enter = wrapped_enter
    out = {}
    try:
        SS = N.load_inst("data/intraday_long/QQQ_1m.parquet")
        for label, kw in (("IB-mid pullback R2 (QQQ native)", {}),):
            cap.clear()
            T, _fn = N.collect(SS, **kw)
            if len(T):
                T = T.copy()
                T["dir"] = T["d"]
                out[label] = T
    finally:
        N.mk = orig
        N.enter = orig_enter
    return out


# ------------------------------------------------------------------ report --
def summarise(name, T, rcol="R"):
    if T is None or not len(T) or rcol not in T:
        return None
    T = T.dropna(subset=[rcol]).copy()
    r = T[rcol].to_numpy(float)
    days = T["day"].unique()
    mo = months_of(days)
    d = dict(strategy=name, trades=len(T), sessions=len(days), months=mo,
             per_mo=len(T) / max(mo, 1), expR=float(r.mean()),
             pf=pf(r), ddR=dd_R(r),
             has_time=("m" in T.columns and T["m"].notna().any()))
    if "dir" in T:
        d["longN"] = int((T["dir"] > 0).sum())
        d["shortN"] = int((T["dir"] < 0).sum())
    for label, a, b in TOD:
        d[label] = (int(((T["m"] >= a) & (T["m"] < b)).sum())
                    if d["has_time"] else np.nan)
    return d


def main() -> int:
    lib, notes = {}, []

    print("RP-008 STAGE 0 -- strategy and entry-time audit. COUNTS ONLY.")
    print("  No conditional performance is computed anywhere in this run.\n")

    print("  building ORB / pullback (QQQ, or_height + setup_grading) ...",
          flush=True)
    lib.update(orb_and_pullback())

    print("  building IB family (reopen_study) ...", flush=True)
    lib.update(ib_family_times())

    print("  building ORB-Fibonacci continuation (orb_fib) ...", flush=True)
    lib.update(orb_fib_times())

    print("  building compressed-range continuation (compression) ...",
          flush=True)
    cs, cnote = compression_sets()
    lib.update(cs)
    notes.extend(cnote)

    print("  building IB midpoint pullback R2 (ib_pullback_native) ...",
          flush=True)
    lib.update(ib_midpoint_pullback())

    rows = [summarise(k, v) for k, v in lib.items()]
    rows = [r for r in rows if r]
    R = pd.DataFrame(rows).sort_values("trades", ascending=False)
    R.to_csv(OUT / "rp008_stage0_strategies.csv", index=False)

    pd.set_option("display.width", 220)
    print("\n=== UNCONDITIONAL STRATEGY INVENTORY ===")
    cols = ["strategy", "trades", "sessions", "months", "per_mo", "expR",
            "pf", "ddR", "longN", "shortN"]
    print(R[[c for c in cols if c in R]].to_string(index=False,
                                                   float_format="%.3f"))

    print("\n=== TRADES BY FROZEN TIME-OF-DAY BLOCK ===")
    tcols = ["strategy", "trades"] + [t[0] for t in TOD]
    print(R[[c for c in tcols if c in R]].to_string(index=False))

    print("\n=== SHARE BY BLOCK ===")
    P = R.copy()
    for t, _a, _b in TOD:
        P[t] = 100 * P[t] / P["trades"]
    print(P[[c for c in tcols if c in P]].to_string(index=False,
                                                    float_format="%.1f"))

    if notes:
        print("\n=== NOTES ===")
        for n in notes:
            print("  " + n)

    print("\n  Sealed NQ dates not read. 2016-2020 not opened. "
          "No regime was applied and no conditional number was produced.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
